---
title: "Amalie - browser"
output: 
  html_document:
    css: custom.css
runtime: shiny
---

# {.tabset}
## dHRUM - The parametrisation of single HRU unit 

```{r petr, echo = FALSE, message = FALSE, warning = FALSE}
shinyAppFile(appFile = "./R/petr/app.R",
             options = list(width = "100%",
                            height = 1000))
```


## Filip - data

```{r phill, echo = FALSE, message=FALSE}
library(sf); library(leaflet); library(data.table)

hru <- st_read(dsn = "./data/hru_info.shp")
tmst <- fread(input = "./data/soil_moisture_sensor_info.csv")
dendro <- fread(input = "./data/dendrometer_info.csv")
vrty <- fread(input = "./data/vrty_info.csv")
vrty <- vrty[vrty$Stav == "Ano",]


head(x = hru)

leaflet() %>% 
  addTiles(group = "Podkladová mapa") %>%
  addWMSTiles(baseUrl = "http://geoportal.cuzk.cz/WMS_ORTOFOTO_PUB/WMService.aspx",
              options = WMSTileOptions(format = "image/png",
                                       crs = "EPSG:102066"),
              layers = "GR_ORTFOTORGB",
              group = "Ortofoto") %>%
  addMarkers(data = vrty,
             lng = ~X,
             lat = ~Y,
             label = paste("Vrt:",
                           vrty$name),
             clusterOptions = markerClusterOptions(),
             group = "Vrty") %>% 
  addMarkers(data = tmst,
             lng = ~X,
             lat = ~Y,
             label = paste("Vlkhost senzor:",
                           tmst$serial_number),
             clusterOptions = markerClusterOptions(),
             group = "Vlhkostní senzory") %>% 
  addMarkers(data = dendro,
             lng = ~X,
             lat = ~Y,
             label = paste("Dendrometr:",
                           dendro$ID),
             clusterOptions = markerClusterOptions(),
             group = "Dendrometry") %>% 
  addPolygons(data = hru,
              label = ~paste(ID, 
                             as.character(x = OBJECTID)),
              popup = paste(
                "<u><b>Informace o HRU:</b></u>",
                paste("<b>Land use/cover:</b> ", hru$Land_Use),
                paste("<b>Plocha:</b> ", round(x = hru$Area, 
                                       digits = 2), 
                      "m<sup>2</sup>"),
                paste("<b>Sklonitost:</b> ", round(x = hru$Slope, 
                                            digits = 2)),
                sep = "</br>"
              ),
              fillColor = "#0EFCAA",
              color = "#05A870",
              weight = 1.75,
              highlight = highlightOptions(
                weight = 2.5,
                fillOpacity = 0.69),
              group = "Polygony hydr. jednotek") %>%
  addLayersControl(baseGroups = c("Podkladová mapa", 
                                  "Ortofoto"),
                   overlayGroups = c("Polygony hydr. jednotek", 
                                     "Vrty",
                                     "Vlhkostní senzory",
                                     "Dendrometry"),
                   options = layersControlOptions(collapsed = TRUE))

# shinyAppFile(appFile = "./R/filip/shiny_placeholder.R",
#              options = list(width = "100%",
#                             height = 1000))
```



<!-- ## dHRUM - HRU jednotka -->

<!-- ```{r eleni, echo = FALSE, message = FALSE, warning = FALSE} -->
<!-- shinyAppFile(appFile = "./R/eleni/app.R", -->
<!--              options = list(width = "100%", -->
<!--                             height = 1000)) -->
<!-- ``` -->


